[![Open In Colab](https://colab.research.google.com/assets/colab-badge.svg)](https://colab.research.google.com/github/Chouksey-Arnav/Data-Science-and-ML-coding-Notebooks/blob/main/Pandas/01-dataframes-with-pandas.ipynb)

In [182]:
#First do ALL necessary imports
import matplotlib.pyplot as plt
import numpy as np
import pandas as pd

#Dataframes with Pandas

Structure inside of a DataFrame in Pandas
#df = pd.DataFrame(data, index, columns, dtype, copy)

In [183]:
#example: 
df=pd.DataFrame( np.random.randn(5,4), ['A', 'B', 'C', 'D', 'E'], ['W','X','Y','Z']) #create a example DataFrame with Pandas

In [184]:
df #Run and take a loook at our random DataFrame

          W         X         Y         Z
A  0.634057  0.816049 -0.830241  0.649957
B  0.159750  1.186074  1.020276  0.817919
C -0.072116  1.129178  2.531513  2.317154
D  1.840882  0.075093 -2.395271  1.021526
E  1.223990 -1.376843  0.039867 -0.139275

A data frame is just a bunch of series that are glued together. Let's take a look at how this is true, and let's prove this out.

In [185]:
df['W'] #Looks exactly like a series

A    0.634057
B    0.159750
C   -0.072116
D    1.840882
E    1.223990
Name: W, dtype: float64

In [186]:
type(df['W']) #This shows us how it ijust taking the W column it is just a Pandas Series, but if we find the type of the entire DataFrame...

pandas.Series

In [187]:
type(df) #This shows that the entire data frame is indeed a pandas data frame, while just a singular column is a pandas series. This helps to reinstate the fact that a data frame is just a bunch of pandas series glued together.

pandas.DataFrame

In [188]:
#When requesting a column from a DataFrame, always use this sort of a Bracket notation.
Example= df['Y']
Example

A   -0.830241
B    1.020276
C    2.531513
D   -2.395271
E    0.039867
Name: Y, dtype: float64

Now... What if I want two series (two columns from our pre-made pandas (random) DataFrame??

In [189]:
df[['X','Z']] #MAKE sure you have two brackets in here!

          X         Z
A  0.816049  0.649957
B  1.186074  0.817919
C  1.129178  2.317154
D  0.075093  1.021526
E -1.376843 -0.139275

Understand this, though: if you're asking for multiple columns, you will get back a data frame. That will be the type, but if you ask for a singular column, you will be getting back a series. That'll be that type.

Now let's create a new column in pandas called `new`.

In [190]:
df['new']=df['X']+df['Z'] #This will run with no errors

In [191]:
df #DF with new 'new' (no pun intented) column added onto it!

          W         X         Y         Z       new
A  0.634057  0.816049 -0.830241  0.649957  1.466006
B  0.159750  1.186074  1.020276  0.817919  2.003992
C -0.072116  1.129178  2.531513  2.317154  3.446332
D  1.840882  0.075093 -2.395271  1.021526  1.096619
E  1.223990 -1.376843  0.039867 -0.139275 -1.516118

We can also remove either columns or rows in pandas by using the `df.drop` method.

In [192]:
#To remove a Column (Up to down)
df.drop('new', axis=1, )

          W         X         Y         Z
A  0.634057  0.816049 -0.830241  0.649957
B  0.159750  1.186074  1.020276  0.817919
C -0.072116  1.129178  2.531513  2.317154
D  1.840882  0.075093 -2.395271  1.021526
E  1.223990 -1.376843  0.039867 -0.139275

In [301]:
#To remove a row (Left to Right)
df.drop('A', axis=0)
df

          W         X         Y         Z
A  0.658216  0.360127 -0.974750 -1.247932
B -0.876829  0.739725 -0.436843 -0.923325
C -0.615381 -0.402070  1.792731 -0.192050
D  0.131830  0.356509 -1.786190 -1.646603
E -0.090951 -0.650493  1.624665  0.611586

The difference between axis=0 and axis=1 in the df.drop method (and in future Pandas methods) is telling us whether to remove the column or the row.
axis=0 tells it to remove a row (left to right), while axis=1 tells us to remove a column (top to bottom)

In [194]:
df

          W         X         Y         Z       new
A  0.634057  0.816049 -0.830241  0.649957  1.466006
B  0.159750  1.186074  1.020276  0.817919  2.003992
C -0.072116  1.129178  2.531513  2.317154  3.446332
D  1.840882  0.075093 -2.395271  1.021526  1.096619
E  1.223990 -1.376843  0.039867 -0.139275 -1.516118

A LOT of pandas methods also have a inplace arguement which tells is if we want a arguement to actually alter the dataFrame so when we use it in the furure the dataframe is actually altered

For example, most pandas methods that use this in-place argument are set to `False`. If we add it so that `inplace` is `True` after the `axis` argument, then if I take out something with the `df.drop` function, for example, like `new`, it stays that way.

In a normal one, without putting `inplace` to be `True` or `False`, it might still show that `drop` function. When I run that specific drop function. The new column won't show because I've dropped it for that specific time, but then, when I rerun `df` in a whole new cell, it will still show up with the new column (because `in place` is automatically preset to `false` unless I reinstate it otherwise).

In [195]:
df # Even though we have 'dropped' columns and rows before since inplace was set to false it is not showed.

          W         X         Y         Z       new
A  0.634057  0.816049 -0.830241  0.649957  1.466006
B  0.159750  1.186074  1.020276  0.817919  2.003992
C -0.072116  1.129178  2.531513  2.317154  3.446332
D  1.840882  0.075093 -2.395271  1.021526  1.096619
E  1.223990 -1.376843  0.039867 -0.139275 -1.516118

In [196]:
#Here is where inplace is set to true
df.drop('new', axis=1, inplace=True)

In [197]:
df

          W         X         Y         Z
A  0.634057  0.816049 -0.830241  0.649957
B  0.159750  1.186074  1.020276  0.817919
C -0.072116  1.129178  2.531513  2.317154
D  1.840882  0.075093 -2.395271  1.021526
E  1.223990 -1.376843  0.039867 -0.139275

In [198]:
#As you can see, the new column has been completely dropped!

Now let's talk about selecting rows. We've already talked about selecting columns, where you just put df and then brackets, and you just put the column name (for example, `y`). Now let's get into selecting rows.

In [199]:
#Here is he data frame again....
df

          W         X         Y         Z
A  0.634057  0.816049 -0.830241  0.649957
B  0.159750  1.186074  1.020276  0.817919
C -0.072116  1.129178  2.531513  2.317154
D  1.840882  0.075093 -2.395271  1.021526
E  1.223990 -1.376843  0.039867 -0.139275

You can select rows in pandas in two ways. Either through the df.loc function or through the df.iloc function. KEEP IN MIND THEY USE BRACKETS [] instead of parenthesis (), which is kinda wierd when starting off

In [200]:
df.loc['A']

W    0.634057
X    0.816049
Y   -0.830241
Z    0.649957
Name: A, dtype: float64

In [201]:
#Or you can do....
df.iloc[0]

W    0.634057
X    0.816049
Y   -0.830241
Z    0.649957
Name: A, dtype: float64

Both of these are Pandas Series as well.

You are also able to select a specific number in a pandas data frame by using the loc function as well....

In [202]:
df #Current Dataframe

          W         X         Y         Z
A  0.634057  0.816049 -0.830241  0.649957
B  0.159750  1.186074  1.020276  0.817919
C -0.072116  1.129178  2.531513  2.317154
D  1.840882  0.075093 -2.395271  1.021526
E  1.223990 -1.376843  0.039867 -0.139275

In [203]:
#Say I want the number -0.067855, I can do this...

In [204]:
df.loc['C','Y'] #This is how I can pull a specific number out of a pandas DataFrame.

np.float64(2.5315132292418525)

In [205]:
# Say I want W and X on C and D. To pull entire numbers out of dataframes using loc, we can....

In [206]:
df.loc[['C','D'],['W', 'X']] #Just like this, I am able to pull out specific numbers out of a DataFrame using loc function.

          W         X
C -0.072116  1.129178
D  1.840882  0.075093

# DataFrames: Part 2

In [207]:
df #Here is our DataFrame

          W         X         Y         Z
A  0.634057  0.816049 -0.830241  0.649957
B  0.159750  1.186074  1.020276  0.817919
C -0.072116  1.129178  2.531513  2.317154
D  1.840882  0.075093 -2.395271  1.021526
E  1.223990 -1.376843  0.039867 -0.139275

In [208]:
#If we want to perform operations on DataFrames, we usually get back a DataFrame of Booleans. Ex. Ask which numbers are greater 0
bool_df=df>0

In [209]:
bool_df

       W      X      Y      Z
A   True   True  False   True
B   True   True   True   True
C  False   True   True   True
D   True   True  False   True
E   True  False   True  False

### Where the number in the data frame is greater than zero, it will stay true, and where the number in the data frame isn't, it will stay false. So it's giving back a boolean

In [210]:
df[df['W']>0] #This only gives the rows where the statement is true, ruturning all rows except c.

          W         X         Y         Z
A  0.634057  0.816049 -0.830241  0.649957
B  0.159750  1.186074  1.020276  0.817919
D  1.840882  0.075093 -2.395271  1.021526
E  1.223990 -1.376843  0.039867 -0.139275

In [211]:
df #Reminder of what the data frame looks like.

          W         X         Y         Z
A  0.634057  0.816049 -0.830241  0.649957
B  0.159750  1.186074  1.020276  0.817919
C -0.072116  1.129178  2.531513  2.317154
D  1.840882  0.075093 -2.395271  1.021526
E  1.223990 -1.376843  0.039867 -0.139275

In [212]:
resultdf=df[df['W']<0] #Since we're asking for the full data frame, it gives us the full data frame, but only where W's value is less than 0.

In [213]:
resultdf

          W         X         Y         Z
C -0.072116  1.129178  2.531513  2.317154

In [214]:
#We can perform specific operations on result df variable

In [215]:
resultdf['X'] #Only pulling out the result out the the x column

C    1.129178
Name: X, dtype: float64

In [216]:
df[df['W']>0]["X"]
#What this means....

A    0.816049
B    1.186074
D    0.075093
E   -1.376843
Name: X, dtype: float64

In [217]:
df

          W         X         Y         Z
A  0.634057  0.816049 -0.830241  0.649957
B  0.159750  1.186074  1.020276  0.817919
C -0.072116  1.129178  2.531513  2.317154
D  1.840882  0.075093 -2.395271  1.021526
E  1.223990 -1.376843  0.039867 -0.139275

# What this basically means is this: Is all this saying: return the data frame where the column value of W happens to be greater than 0, and this returns the entire data frame

### Shift to MULTIPLE CONDITIONS in Python

In [218]:
df[(df['W']>0) & (df['Z']>-1)]

          W         X         Y         Z
A  0.634057  0.816049 -0.830241  0.649957
B  0.159750  1.186074  1.020276  0.817919
D  1.840882  0.075093 -2.395271  1.021526
E  1.223990 -1.376843  0.039867 -0.139275

The 'OR operator in pandas

In [219]:
#| is the or operator. I can use it
df[(df['W']>0) | (df['Z']>-1)]

          W         X         Y         Z
A  0.634057  0.816049 -0.830241  0.649957
B  0.159750  1.186074  1.020276  0.817919
C -0.072116  1.129178  2.531513  2.317154
D  1.840882  0.075093 -2.395271  1.021526
E  1.223990 -1.376843  0.039867 -0.139275

In [220]:
df

          W         X         Y         Z
A  0.634057  0.816049 -0.830241  0.649957
B  0.159750  1.186074  1.020276  0.817919
C -0.072116  1.129178  2.531513  2.317154
D  1.840882  0.075093 -2.395271  1.021526
E  1.223990 -1.376843  0.039867 -0.139275

In [221]:
#To reset the index you can use this method
df.reset_index() #If you make this to be permanant you can set inplace=True

  index         W         X         Y         Z
0     A  0.634057  0.816049 -0.830241  0.649957
1     B  0.159750  1.186074  1.020276  0.817919
2     C -0.072116  1.129178  2.531513  2.317154
3     D  1.840882  0.075093 -2.395271  1.021526
4     E  1.223990 -1.376843  0.039867 -0.139275

In [222]:
newind= 'CA NY WY OR CO'.split() #Remember, `.split` just splits based on spaces.

In [223]:
newind

['CA', 'NY', 'WY', 'OR', 'CO']

In [224]:
df['States']=newind
df #We see a new states columns addeed on that we just created!

          W         X         Y         Z States
A  0.634057  0.816049 -0.830241  0.649957     CA
B  0.159750  1.186074  1.020276  0.817919     NY
C -0.072116  1.129178  2.531513  2.317154     WY
D  1.840882  0.075093 -2.395271  1.021526     OR
E  1.223990 -1.376843  0.039867 -0.139275     CO

In [225]:
df.set_index('States')#We can also use `set_index` to set a new index. And to make this permanent, you'd need to add `in place = true`.

               W         X         Y         Z
States
CA      0.634057  0.816049 -0.830241  0.649957
NY      0.159750  1.186074  1.020276  0.817919
WY     -0.072116  1.129178  2.531513  2.317154
OR      1.840882  0.075093 -2.395271  1.021526
CO      1.223990 -1.376843  0.039867 -0.139275

# DataFrames -- Part 3:

In [284]:
# Index Levels
outside = ['G1','G1','G1','G2','G2','G2']
inside = [1,2,3,1,2,3]
hier_index = list(zip(outside,inside))
hier_index = pd.MultiIndex.from_tuples(hier_index)
#Multiindex?? You will see....

In [285]:
df_2=pd.DataFrame(np.random.randn(6,2),index=hier_index,columns=['A','B'])
df_2 #Shows the multi index

             A         B
G1 1  0.389929  0.582440
   2 -0.674164 -1.383751
   3  0.255802 -0.463015
G2 1  0.051497 -0.720562
   2  0.469912  0.538341
   3  0.963836 -0.968410

In [286]:
df_2

             A         B
G1 1  0.389929  0.582440
   2 -0.674164 -1.383751
   3  0.255802 -0.463015
G2 1  0.051497 -0.720562
   2  0.469912  0.538341
   3  0.963836 -0.968410

### Now Lets show how to index this? For the index hierarchy, we can use `df.loc`, and if this was on the column axis, you could just use normal bracket notation `df[]`.

In [287]:
df_2.loc['G1'] #Gives you the 'Subsection' under G1

          A         B
1  0.389929  0.582440
2 -0.674164 -1.383751
3  0.255802 -0.463015

In [288]:
df_2.loc['G1'].loc[1] #You can keep on going deeper as well

A    0.389929
B    0.582440
Name: 1, dtype: float64

In [289]:
df_2.index.names

FrozenList([None, None])

df.index.names

df.index.names is a property that returns the names of the row-index levels, not the individual row labels. It is accessed without parentheses.

A single-level index has one name; a MultiIndex has one name per level.

An unnamed level is represented by None.

When assigning names, the number of names must match the number of index levels.

python
df.index.names                         # View index-level names
df.index.names = ["Student"]           # Name a single-level index
df.index.names = ["Student", "Subject"] # Name an existing two-level index

In this data frame where it's a multi-index, you can do more than one for `df.index.names`, but in a normal data frame with just one index, it'll give you an issue if you try to do more than one. You just look at how many indexes you currently have.

In [290]:
#For example we can calll this outside index 'Groups and inside index 'num'
df_2.index.names = ['Group','Num']

In [292]:
df_2 #Changes df(2) with indexnames there

                  A         B
Group Num
G1    1    0.389929  0.582440
      2   -0.674164 -1.383751
      3    0.255802 -0.463015
G2    1    0.051497 -0.720562
      2    0.469912  0.538341
      3    0.963836 -0.968410

In [ ]:
#Seltcting specific values from df(2) by indexing

In [297]:
df_2.loc['G1'].loc[1]['B'] #Like this you are able to select any value

np.float64(0.582439774824524)

In [299]:
#For example, If I wanted 0.963836 from the table
df_2.loc['G2'].loc[3]['A']

np.float64(0.9638358066133532)

One last VERY USEFUL function called .xs in DataFrame, this is the cross section method

In [300]:
df_2.xs(1, level='Num')

              A         B
Group
G1     0.389929  0.582440
G2     0.051497 -0.720562