[![Open In Colab](https://colab.research.google.com/assets/colab-badge.svg)](https://colab.research.google.com/github/Chouksey-Arnav/Data-Science-and-ML-coding-Notebooks/blob/main/Pandas/02-missing-data.ipynb)

# Missing Data Lecture by Jose Portilla

In [4]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt#
#Import all necessary libraries.

In [7]:
#Lets start with creating a DataFrame
dictionary= {'A':[1,2,np.nan],'B':[5,np.nan,np.nan], 'C':[1,2,3]}

In [10]:
df=pd.DataFrame(dictionary)
df
#np.nan shows null values to show that ythere is no data there. Stands for "Not A Number"

     A    B  C
0  1.0  5.0  1
1  2.0  NaN  2
2  NaN  NaN  3

### You have a DataFrame with Null Values as you can see

In [12]:
#New method: df.dropna(), this method drops all rows (or columns) wiht null values
df.dropna() #Only returns the first row since all the other rows have AT LEAST one null value

     A    B  C
0  1.0  5.0  1

In [14]:
#But, if I want, I could also make `df.dropna() drop columns
df.dropna(axis=1) #Recall, we talked about this in the First notebook in Pandas on DataFrames
#This method drops all of the columns with a null value.

   C
0  1
1  2
2  3

In [16]:
df.dropna()

     A    B  C
0  1.0  5.0  1

In [18]:
#this method also has a thresh input that you can put in....
df.dropna(axis=0,thresh=2)

     A    B  C
0  1.0  5.0  1
1  2.0  NaN  2

This means that if something has 2 numbers then it still goes over the 'Threshold' even though it has 1 NaN (null) value

Now we can use the df.fillna method which helps us, if we have null values, then we can fill them in.

In [21]:
#Here is how it works....
df.fillna(value='FILL VALUE') #You will see the NaN or null values to be filled now!

            A           B  C
0         1.0         5.0  1
1         2.0  FILL VALUE  2
2  FILL VALUE  FILL VALUE  3

In [35]:
df['A'].fillna(value=df['A'].mean())

0    1.0
1    2.0
2    1.5
Name: A, dtype: float64

Throughout this entire Jupiter notebook, we've talked about two methods with data frames: `df.dropna` and `df.fillna`.

For `df.dropna`, you are able to drop rows and columns based on the axis that has null values. You are also able to set `axis` and `threshold` values as parameters. If you want to tweak how much you want to drop based on the null values as well, then there's `df.fillna`, where you can fill specific null values in tables as well.

At the end, keep in mind none of these actually get saved because `inplace` is automatically set to `False` as the boolean. If you were to set `inplace` to `True`, then all these changes to the data frame would actually save.