[![Open In Colab](https://colab.research.google.com/assets/colab-badge.svg)](https://colab.research.google.com/github/Chouksey-Arnav/Data-Science-and-ML-coding-Notebooks/blob/main/Pandas/03-group-by.ipynb)

# Lecture number 3: Group By

Explanation of Groupby: `GROUP BY` allows you to group together rows based on a column and perform an aggregate function on them.

In [10]:
import pandas as pd
import numpy as np
import matplotlib as plt
#import all out necessary libraries here

In [11]:
data = {'Company':['GOOG','GOOG','MSFT','MSFT','FB','FB'],
       'Person':['Sam','Charlie','Amy','Vanessa','Carl','Sarah'],
       'Sales':[200,120,340,124,243,350]}
#Dictionary for data

In [12]:
df=pd.DataFrame(data)

In [13]:
df #Here is the OG, current loook of df that we got from the Dictionary we created!

  Company   Person  Sales
0    GOOG      Sam    200
1    GOOG  Charlie    120
2    MSFT      Amy    340
3    MSFT  Vanessa    124
4      FB     Carl    243
5      FB    Sarah    350

In [21]:
#Lets Groupby the Company column
byComp=df.groupby('Company')

In [15]:
#Then we are able to perform aggregate functions on what we have grouped by.

In [33]:
byComp['Sales'].mean() 
#As you can see the Group by, literally 'Groups By' Company so we get three different values. For the three different companies that we have grouped by here

Company
FB      296.5
GOOG    160.0
MSFT    232.0
Name: Sales, dtype: float64

In [25]:
byComp['Sales'].sum() #Group by comes in handy here as well

Company
FB      593
GOOG    320
MSFT    464
Name: Sales, dtype: int64

In [27]:
byComp['Sales'].sum().loc['GOOG'] #We can also use row indexing here too!

np.int64(320)

In [37]:
#But, we usually dont save the groupby in a variable like we have done here for explanatory purposes.
#Instead we can do it all in one line which is MUCH more efficient and easier once you get the hand of it!
df.groupby('Company')['Sales'].sum().loc['GOOG'] #We are able to get to the values MUCH quicker like this!

np.int64(320)

In [38]:
df #Again this is the Database for better referance

  Company   Person  Sales
0    GOOG      Sam    200
1    GOOG  Charlie    120
2    MSFT      Amy    340
3    MSFT  Vanessa    124
4      FB     Carl    243
5      FB    Sarah    350

In [39]:
df.groupby('Company')['Sales'].max()

Company
FB      350
GOOG    200
MSFT    340
Name: Sales, dtype: int64

In [42]:
df.groupby('Company').describe() #This function helps tell you a lot of the data for each company (in this case)!

        Sales
        count   mean         std    min     25%    50%     75%    max
Company
FB        2.0  296.5   75.660426  243.0  269.75  296.5  323.25  350.0
GOOG      2.0  160.0   56.568542  120.0  140.00  160.0  180.00  200.0
MSFT      2.0  232.0  152.735065  124.0  178.00  232.0  286.00  340.0

In [45]:
df.groupby('Company').describe().loc['MSFT'] #You can also look at specifics with .loc function for a specific company.

Sales  count      2.000000
       mean     232.000000
       std      152.735065
       min      124.000000
       25%      178.000000
       50%      232.000000
       75%      286.000000
       max      340.000000
Name: MSFT, dtype: float64